#Simple workfow to build CoreELEC for Phicomm N1
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the n1-19 branch
  push:
    branches: [ n1-19 ]
  pull_request:
    branches: [ n1-19 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Initialization Environment
        run: |
          echo $CUSTOM_VERSION
          git branch -v
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/share/man
          sudo -E apt-get -qq update
          sudo -E apt-get install gcc make git unzip wget xz-utils bc gperf zip unzip g++  build-essential patchutils lzop xfonts-utils xsltproc libjson-perl cmake texinfo default-jre libncurses5-dev file zstd libparse-yapp-perl
          sudo -E apt-get -qq autoremove --purge

      - name: Cache downloaded packages
        uses: actions/cache@v2
        with:
          path: sources
          key: ${{ runner.os }}-${{ hashFiles('./mkn1') }}

      - name: Run build
        run: ./mkn1
      
